### ISSUE TITLE
Using Node.js 12.4.0?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [hoosin/alpine-nginx-nodejs#11]
Latest still gives me node v10.16.0 but the table on the readme shows v12.4.0.
To be fair the note above it does say the latest tag is on v10.16.0 but it is inconsistent with the table.

To use 12.4.0 thought I could just run this.
```bash
apk add --no-cache --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main nodejs=14.2.0-r0 nodejs-npm=14.2.0-r0
```

But it gives ```ERROR: unsatisfiable constraints```

Highest it seems I can go is 12.6.3 not ideal as I wanted 12.4.0 but eh.
```bash
apk add --no-cache --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main nodejs=12.16.3-r0 nodejs-npm=12.16.3-r0 yarn=1.7.0-r0 libuv=1.37.0-r0
```

At least now I can yarn add puppeteer.

**Comment by hoosin** [comment]
@LiamKarlMitchell https://github.com/hoosin/alpine-nginx-nodejs/commit/1f85ac670847905c421fad3658c6c785bd600020
