### ISSUE TITLE
Tag latest image with specific version

### ISSUE THREAD

**Issue by CyprianSz** [hoosin/alpine-nginx-nodejs#12]
Hello, 

thanks for an image. If I may have a request, could you please tag latest version of it with a specific version number (hoosin/alpine-nginx-nodejs:12.18.0). I don't want it to change when you release the new one.

Thanks from advance,
Regards

**Comment by hoosin** [comment]
https://github.com/hoosin/alpine-nginx-nodejs/commit/bf858925203a4df5af90b24f1720283f5f0a1329

Upgrading to the latest version and image is successfully built:
https://hub.docker.com/layers/59025208/hoosin/alpine-nginx-nodejs/latest/images/sha256-a21c4dbbcd9451d3aeceae2e46eca5971af2c50e15096893895424f5e5a68e08?context=explore


@CyprianSz
